---
title: "Orb_EX_AB_sym_analysis"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(devtools)   # install.packages("devtools")
library(steponeR) # install_github("jrcunning/steponeR")
library(tidyverse) # (install.packages("tidyverse")
```


#Importing Raw qPCR Data from Quant Studio Design and Analysis Software 
```{r}
# List Exuma symbiodinium data files
plates_EX <- list.files(path = "Data/qPCR_EX", pattern = ".txt", full.names = TRUE)
plates
# Read in data and calculate target ratios
df_EX <- steponeR(files = plates_EX,
               delim = "\t", 
               target.ratios = "A.A", 
               fluor.norm = list(C = 2.234, D = 1, A = 1, B = 1),
               copy.number = list(C = 20, D = 3, A = 1, B = 1),
               ploidy = list(C = 1, D = 1, A = 1, B = 1),
               extract = list(C = 0.813, D = 0.813, A = 0.813, B = 0.813))
qpcr_EX <- df_EX$result

```

#Filtering out other species from EX Raw qPCR data
```{r}
# Import Sample Data 
library(readr)

raw_sample_data <- readxl::read_xlsx("Data/Sample_data/Ex_Sample_Data.xlsx")

#renaming  colomns of sample data to match qpcr data
sample_data_EX <- raw_sample_data %>%
  select(Sample.Name = sample_id, site, genus, species, depth = colony_depth_m, range)

# Joining sample data with qpcr data and removing NA samples
EX_Ofav <- right_join(sample_data_EX, qpcr_EX, by = "Sample.Name", all = TRUE) %>%
  filter(genus == "orbicella")

qpcr_EX_Ofav <- EX_Ofav %>%
  select(Sample.Name, File.Name, depth, A.CT.mean, B.CT.mean, C.CT.mean, D.CT.mean, A.CT.sd, B.CT.sd, C.CT.sd,
         D.CT.sd, A.reps, B.reps, C.reps, D.reps, A.A)
```

```{r}
# List Sandy Cay symbiodinium data files
plates_AB <- list.files(path = "Data/qPCR_AB", pattern = ".txt", full.names = TRUE)
plates
# Read in data and calculate target ratios
df_AB <- steponeR(files = plates_AB, 
               delim = "\t", 
               target.ratios = "A.A", 
               fluor.norm = list(C = 2.234, D = 1, Orb = 1, A = 1, B = 1),
               copy.number = list(C = 20, D = 3, Orb = 1, A = 1, B = 1),
               ploidy = list(C = 1, D = 1, Orb = 2, A = 1, B = 1),
               extract = list(C = 0.813, D = 0.813, Orb = 0.982, A = 0.813, B = 0.813))
qpcr_AB <- df_AB$result %>%
  select(Sample.Name, File.Name, A.CT.mean, B.CT.mean, C.CT.mean, D.CT.mean, A.CT.sd, B.CT.sd, C.CT.sd,
         D.CT.sd, A.reps, B.reps, C.reps, D.reps, A.A)
```

#Import Depth Data and Add to qpcr_good df
```{r}
#library(readr)
sample_data_AB <- readxl::read_xlsx("Data/Sample_data/sample_data.xlsx") %>%
  select(Sample.Name = tube_label, depth = colony_depth_m)

qpcr_AB_Ofav <- right_join(sample_data_AB, qpcr_AB, by = "Sample.Name", all = TRUE)

```

```{r}
Ofav_qpcr <- rbind(qpcr_EX_Ofav, qpcr_AB_Ofav)
```

# Establishing Ratios
```{r}
# adjust CT for flouresence 
qpcr_flor <-Ofav_qpcr %>%
  mutate(A.CT.mean = A.CT.mean - 1, 
         B.CT.mean = B.CT.mean - 1,
         C.CT.mean = C.CT.mean - 1,
         D.CT.mean = D.CT.mean - 1)

# adjust CT to form ratio of Symbiont divided by Copy # (Currently a Placeholder #)
qpcr_copy_num <- qpcr_flor %>%
  mutate(N = 15) %>%
  mutate(A.N = 2^(N - A.CT.mean)/1,
         B.N = 2^(N - B.CT.mean)/1,
         C.N = 2^(N - C.CT.mean)/1,
         D.N = 2^(N - D.CT.mean)/1)

qpcr_prop <- qpcr_copy_num %>%
  mutate(A.N = ifelse(is.na(A.N), 0, A.N),
         B.N = ifelse(is.na(B.N), 0, B.N),
         C.N = ifelse(is.na(C.N), 0, C.N),
         D.N = ifelse(is.na(D.N), 0, D.N)) %>%
  rowwise() %>%
  mutate(total = sum(A.N + B.N + C.N + D.N))%>%
  mutate(A.prop = A.N/total, B.prop = B.N/total, C.prop = C.N/total, D.prop = D.N/total)

qpcr_symname <- qpcr_prop %>%
  mutate(dom_sym = case_when(B.prop > C.prop & B.prop > D.prop & B.prop > A.prop ~ "Breviolum",
                             C.prop > B.prop & C.prop > D.prop & C.prop > A.prop ~ "Cladocopium",
                             D.prop > B.prop & D.prop > C.prop & D.prop > A.prop ~ "Durusdinium",
                             A.prop > B.prop & A.prop > C.prop & A.prop > D.prop ~ "Symbiodinium"))
   
```


# Oranizing Raw qPCR Data
```{r}
# Convert NaN CT values to 0  
qpcr <- qpcr_symname %>%
 mutate(A.CT.mean = ifelse(is.na(A.CT.mean), 0, A.CT.mean),
         B.CT.mean = ifelse(is.na(B.CT.mean), 0, B.CT.mean),
         C.CT.mean = ifelse(is.na(C.CT.mean), 0, C.CT.mean),
         D.CT.mean = ifelse(is.na(D.CT.mean), 0, D.CT.mean))

# Samples that did not amplify for any symbionts
fails <- qpcr %>%
  filter(A.CT.mean == 0 & B.CT.mean == 0 & C.CT.mean == 0 & D.CT.mean == 0,
         Sample.Name != "PTC",
         Sample.Name != "NTC")

# Samples that need to be rerun due to 1 technical replicate or SD > 1
reruns <- qpcr %>%
  filter(Sample.Name != "PTC", Sample.Name != "NTC") %>%
  filter(A.reps == 1 | B.reps == 1 | C.reps == 1 | D.reps == 1 | A.CT.sd > 1.05 | B.CT.sd > 1.05 | C.CT.sd > 1.05 | D.CT.sd > 1.05)
```

#Filtering out "bad" data/replicates
```{r}
#Determing which samples have 2 replicates in the data set and did not fail
dupes <- qpcr %>%
  filter(Sample.Name != "PTC", Sample.Name != "NTC") %>%
  filter(!(A.CT.mean == 0 & B.CT.mean == 0 & C.CT.mean == 0 & D.CT.mean == 0)) %>%
  group_by(Sample.Name) %>%
  count(vars = "Sample.Name") %>%
  filter(n > 1) 

#Gathering the full data for samples with 2 replicates
Ofav_dupes <- qpcr %>%
  filter(Sample.Name %in% dupes$Sample.Name) %>%
  arrange(Sample.Name)%>%
  filter(!(A.CT.mean == 0 & B.CT.mean == 0 & C.CT.mean == 0 & D.CT.mean == 0))

#filtering out data with only 1 technical replicate
Ofav_dupes_f1 <- Ofav_dupes %>%
  group_by(Sample.Name) %>%
  filter(A.reps != 1, B.reps != 1, C.reps != 1, D.reps != 1) %>%
  ungroup()
  
# Average SD  
Ofav_dupes_f2 <- Ofav_dupes_f1 %>%
  rowwise() %>%
  mutate(avg_sd = mean(c(A.CT.sd, B.CT.sd, C.CT.sd, D.CT.sd), na.rm = TRUE)) %>%
  group_by(Sample.Name) %>%
  dplyr::filter(avg_sd == min(avg_sd)) 

# Raw Data fine on the first run
qpcr_good <- qpcr %>%
  filter(Sample.Name != "PTC", Sample.Name != "NTC") %>%
  filter(!(Sample.Name %in% reruns$Sample.Name))%>%
  filter(!(Sample.Name %in% fails$Sample.Name))


# Cleaned dataset from data that worked the first run and "clean" replicates 
Ofav_good <- qpcr_good %>%
  filter(!Sample.Name %in% dupes$Sample.Name) %>%
  bind_rows(Ofav_dupes_f2)

need_2_clean <- Ofav_good %>%
  group_by(Sample.Name) %>%
  count(vars = "Sample.Name") %>%
  filter(n > 1) 


# Which Samples Were Duplicated and Still Need to be Rerun?
setdiff(Ofav_dupes$Sample.Name, Ofav_dupes_f2$Sample.Name)
# EX066 and Ex0248 We need to give up on, won't produce 2 technical replicates for certain symbionts
# EX0270 check where it disappears because 1 of 3 should have gotten through
# SC002 and SC004 "   "                                                               "

setdiff(fails$Sample.Name, Ofav_good$Sample.Name)

# Samples that need to be rerun
setdiff(reruns$Sample.Name, Ofav_dupes_f2$Sample.Name)
# Give up on: EX0066, EX0249
# EX0270 from 20190917_KP_01.txt should make it through 
# MR034 and 040 Should make it through 
```

```{r}
Ofav <- Ofav_good %>%
  select(Sample.Name, depth, A.prop, B.prop, C.prop, D.prop, dom_sym)
```

